name: app_oficina
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'

dependencies:
  currency_textfield: ^3.1.0
  dio: ^5.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.0
  searchfield: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
